name: syncre
description: "A Multi-platform Chat Application"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  font_awesome_flutter: ^10.7.0
  http: ^0.13.6
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
